; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
#NoTrayIcon
SetWorkingDir %A_ScriptDir%
FileEncoding, utf-8

_Code := ""
A_jump := A_Start := 20 , y_jump := 33
Loop, 5 {
    A_jump := A_jump + y_jump
    A_row%A_Index% := A_jump 
}
B_jump := B_start := A_row5 + 40
Loop, 2 {
    B_jump := B_jump + y_jump
    B_row%A_Index% :=B_jump 
}
C_jump := C_start := B_row2 + 40
Loop, 2 {
    C_jump := C_jump + y_jump
    C_row%A_Index% := C_jump
}
Gui Color, CCCCFF
Gui Font, S11, Tahoma
Gui Font, Bold
Gui Add, GroupBox, x20 y%A_Start% w1320 h200 cNavy, Thông tin bệnh nhân
Gui Add, GroupBox, x20 y%B_start% w1320 h100 cNavy, Thông tin khám
Gui Add, GroupBox, x20 y%C_start% w1320 h330 cNavy, Đăng ký dịch vụ

Gui, Font, Normal
;A_row1
Gui Add, Text, x40 y%A_row1% w120 h27 +0x200, Mã BN:
Gui Add, Edit, x150 y%A_row1% w110 Disabled +Border,
Gui Add, Text, x280 y%A_row1% h27 +0x200, Họ tên:
Gui Font, Bold
Gui Add, Edit, x340 y%A_row1% w180 CNavy,
Gui FOnt, Normal
Gui Add, Pic, x525 y%A_row1% h27 w30, %A_ScriptDir%\search.png

Gui Add, Text, x570 y%A_row1% h27 +0x200, Giới tính:
Gui Add, DropDownList, x690 y%A_row1% w90 -Theme, Nam||Nữ|Chưa xác định
Gui Add, Text, x790 y%A_row1% h27 +0x200, Ngày sinh:
Gui Add, DateTime, x880 y%A_row1% w110,
Gui Add, Text, x1000 y%A_row1% h27 +0x200, Nghề nghiệp:
Gui Add, DropDownList, x1090 y%A_row1% w230 -Theme, Công nhân||Dịch vụ|Khác
;A_row2
Gui Add, Text, x40 y%A_row2% h27 +0x200, Số nhà/Thôn:
Gui Add, Edit, x150 y%A_row2% w400 vsonha gsonha,
Gui Add, Text, x570 y74 y%A_row2% h27 +0x200, T/H/X:
Gui Add, Edit, x690 y%A_row2% w90 -Theme, HCTDTB
Gui Add, DropDownList, x790 y%A_row2% w130 vtinh gtinh -Theme, Hồ Chí Minh||Đồng Nai
Gui Add, DropDownList, x930 y%A_row2% w150 vhuyen ghuyen -Theme, Quận 1||Quận 2
Gui Add, DropDownList, x1090 y%A_row2% w230 vxa gxa -Theme, Phường 1||Phường 2|Phường 3
;A_row3
Gui Add, Text, x40 y%A_row3% h27 +0x200, ĐC hiện nay:
Gui Add, Edit, x150 y%A_row3% w400 viadd -Theme Disabled, `,Phường 1, Quận 1, Hồ Chí Minh
Gui Add, Text, x570 y%A_row3% w150 h27 +0x200, ĐC thường trú:
Gui Add, Edit, x690 y%A_row3% w90 +Number, LDDTTH
Gui Add, Edit, x790 y%A_row3% w530, Thon 4a
;A_row4
Gui Add, Text, x40 y%A_row4% w98 h27 +0x200, Điện thoại:
Gui Add, Edit, x150 y%A_row4% w120 +right +Number,
Gui Add, Text, x280 y%A_row4% h27 +0x200, Email:
Gui Add, Edit, x350 y%A_row4% w200, Gerhan94@gmail.com
Gui Add, Text, x570 y%A_row4% h27 +0x200, CMND/CCCD:
Gui Add, Edit, x690 y%A_row4% w110 +Number,
Gui Add, Text, x810 y%A_row4% w80 h27 +0x200, Ngày cấp:
Gui Add, DateTime, x880 y%A_row4% w110 h24
Gui Add, Text, x1000 y%A_row4% h27 +0x200, Nơi cấp:
Gui Add, Edit, x1090 y%A_row4% w230
;A_row5
Gui Add, Text, x40 y%A_row5% w150 h27 +0x200, Nơi công tác:
Gui Add, Edit, x150 y%A_row5% w400  +Number
Gui Add, Text, x570 y%A_row5% h27 +0x200, Ngày bắt đầu làm việc:
Gui Add, DateTime, x730 y%A_row5% w110

;Thông tin khám bệnh
Gui Add, Text, x40 y%B_row1% h27 +0x200, Phân loại:
Gui Add, DropDownList, x150 y%B_row1% w400 -theme, Lao động các ngành nghề, công việc||Học sinh các trường
Gui Add, Text, x570 y%B_row1% h27 +0x200, Gói khám:
Gui Add, DropDownList, x690 y%B_row1% w250 -theme, Khám tổng quát||Khám sức khỏe đi xuất khẩu

Gui Add, Text, x40 y%B_row2% h27 +0x200, Phòng khám:
Gui Add, DropDownList, x150 y%B_row2% w400 -theme, Phòng X-Quang 1||Phòng khám sức khỏe ngoại viện
Gui Add, Text, x570 y%B_row2% h27 +0x200, Ngày khám:
Gui Add, Datetime, x690 y%B_row2% w200 disabled +Border, dd/MM/yyyy HH:mm:ss

;Thông tin Dịch vụ
Gui Font, Bold
Gui Add, Text, x40 y%C_row1%, Danh sách dịch vụ
Gui Add, Text, x700 y%C_row1%, Danh sách đã đăng ký
Gui Font, Normal
Gui Add, Edit, x200 y%C_row1% w300 hWndhEdtValue -theme +Border,
SendMessage 0x1501, 1, "Tìm kiếm dịch vụ",, ahk_id %hEdtValue%

Gui Add, Button, x650 y500 gAdd, >>
Gui Add, Button, x650 y540, <<

Gui Add, ListView, x40 y%C_row2% w600 h250 +grid vList1 gList1 AltSubmit -Multi, Mã DV|Tên DV|Đơn giá|Lấy giá gói|Giới tính|Tên viết tắt
    LV_ModifyCol(1, 70)
    LV_ModifyCol(2, 300)
    LV_ModifyCol(3, "100 right")
    LV_ModifyCol(4, "100 Center")
    LV_ModifyCol(5, 80 )
    LV_ModifyCol(6, 100 )
   
Gui Add, ListView, x700 y%C_row2% w620 h250 +grid vList2, Mã DV|Tên DV|Đơn giá|Mã gói khám
    LV_ModifyCol(1, 70)
    LV_ModifyCol(2, 300)
    LV_ModifyCol(3, "100 right")
    LV_ModifyCol(4, "120")

Gui Add,BUtton, x1110 y675 w100, Lưu
Gui Add,BUtton, x1220 y675 w100, Thêm mới
Gui Show, w1366 h715, KSK
readfile()
Return

GuiEscape:
GuiClose:
    ExitApp


Sonha:
Tinh:
Huyen:
Xa:
    Gui Submit, NoHide
    iadd := sonha . ", " . xa . ", " . Huyen . ", " . Tinh
    GuiControl, , iadd, %iadd%
    Return

List1:
    Gui, ListView, List1
    If (A_GuiEvent = "Normal") {
        iRow := A_EventInfo
        LV_GetText(rCode, iRow, 1)
        LV_GetText(rName, iRow, 2)
        LV_GetText(rPrice, iRow, 3)
    }
    Return

Add:
    Gui Submit, NoHide
    _check = 0
    If (iRow <> 0) {
        Loop, Parse, _code, `|
        {
            If (rCode = A_LoopField)
                _check = 1
        }
        If (_check = 1) {
            Msgbox,,Thông báo, Dịch vụ đã chọn rồi
            Return
        }
        _code .= rCode . "|"
        Gui, ListView, List2
        LV_Add("", rCode, rName, rPrice, "ABC")
    }
    iRow := 0
    Return




readfile()
{
    Xpath = %A_ScriptDir%\dv.txt
    Loop {
        icode = CODE%A_Index%
        random, r, 1, 20
        Price := r*100000
        Price := Format_Commas(Price)
        Gender_arr := ["Nam", "Nữ", "Tất cả"]
        Random, s, 1,3
        gender := Gender_arr[s]
        acronym := Randomstring(4)
        FileReadLine, OutputVar, %Xpath%, %A_Index%
        If ErrorLevel
            Break
        Gui, ListView, List1
        LV_Add("", icode, OutputVar, Price, "[ ]",gender, acronym)


    }
}

Format_Commas(val) 
{ 
	Return RegExReplace(val, "(?(?<=\.)(*COMMIT)(*FAIL))\d(?=(\d{3})+(\D|$))", "$0,") 
}

Randomstring(len, i = 65, x = 90) { ; length, lowest and highest Asc value
	Loop, %len% {
		Random, r, i, x
		s .= Chr(r)
	    }
	Return, s
    }